###

// Add product

POST http://localhost:3006/product
Content-Type: application/json

{
  "name": "Nice product",
  "description": "Some text",
  "price": 12
}

###

// Get all products

GET http://localhost:3006/product
Content-Type: application/json

###

// Get single product by ID
// Create one product and fetch it's ID in order to get single product

GET http://localhost:3006/product/5ec2de01394a0b40bd378d63
Content-Type: application/json

###

// Update single product by ID
// Create one product and fetch it's ID in order to update single product

PUT http://localhost:3006/product/5ec2de01394a0b40bd378d63
Content-Type: application/json

{
  "name": "Nice product (Updated)",
  "description": "Some text (Updated)",
  "price": 12.2
}

###

// Delete single product by ID
// Create one product and fetch it's ID in order to delete single product

DELETE http://localhost:3006/product/5ec2de01394a0b40bd378d63
Content-Type: application/json

###
