###

// Add product

POST https://productnco.herokuapp.com/product
Content-Type: application/json

{
  "name": "Nice product",
  "quantity": 10,
  "price": 12,
  "color": "red",
  "image": "url",
  "description": "Some text"
}

###

// Get all products

GET https://productnco.herokuapp.com/product
Content-Type: application/json

###

// Get single product by ID
// Create one product and fetch it's ID in order to get single product

GET https://productnco.herokuapp.com/product/5ec2de01394a0b40bd378d63
Content-Type: application/json

###

// Update single product by ID
// Create one product and fetch it's ID in order to update single product

PUT https://productnco.herokuapp.com/product/5ec2e5708bd68f4388ab95dc
Content-Type: application/json

{
  "name": "Nice product (Updated)",
  "quantity": 105,
  "price": 125,
  "color": "green",
  "image": "url (Updated)",
  "description": "Some text (Updated)"
}

###

// Delete single product by ID
// Create one product and fetch it's ID in order to delete single product

DELETE https://productnco.herokuapp.com/product/5ec2de01394a0b40bd378d63
Content-Type: application/json

###
